# .travis.yml -- Travis CI specification file.
# Copyright 2016-2019 the Tectonic Project
# Licensed under the MIT License.

language: rust

cache: false

matrix:
  include:
    # Linux, Rust stable: the "main" build; we do code coverage, AppImage generation, etc.
    - os: linux
      sudo: required
      dist: xenial
      rust: stable
      env: RUSTFLAGS="-C link-dead-code"
    # Linux, Rust beta: just a smoke test
    - os: linux
      sudo: required
      dist: xenial
      rust: beta
    # Linux, Rust nightly: not even a smoke test; failure is allowed
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
    # MacOS, Rust stable: just a smoke test
    - os: osx
      osx_image: xcode10.2
      rust: stable
  allow_failures:
    - rust: nightly

# Don't CI branches besides master. Pull requests still get CI'd -- but when a
# PR comes in on a branch in the same repo, this prevents it from being CI'd
# twice. Despire the name of this config item, the filtering applies to both
# branch and tag names, so to CI release tags we have to list them here too.
branches:
  only:
    - continuous
    - master
    - /^v\d+\.\d+\.\d+.*$/

addons:
  apt:
    packages:
      - libgraphite2-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
      - libicu-dev
      - libssl-dev
      - openssl
      - zlib1g-dev
  homebrew:
    packages:
      - harfbuzz
      - openssl

install: true
script: source dist/travis.sh
