# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# Step to build and test the Tectonic binary in release mode using the
# rust-embedded "cross" framework.

parameters:
- name: platform
  type: string

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
    displayName: Set up QEMU execution of executable from test suite
  - script: docker run --rm -v $(pwd):/work:rw,Z tectonictypesetting/ttcross:latest
    displayName: Install custom-built cross tool
  - script: |
      ./cross test --target ${{ parameters.platform }} --release --all
    displayName: Build and test
