# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# Triggered when a deployment tag is pushed. This might be either the
# "continuous" tag, for our continuous deployment workflow, or a real release
# tag.

trigger:
  branches:
    include:
      - refs/tags/continuous
      - refs/tags/v*

pr: none

variables:
- template: variables.yml

jobs:
- job: build_and_deploy_cross
  pool:
    vmImage: ${{ variables.linux_image }}

  strategy:
    matrix:
      ${{ each vpair in variables }}:
        ${{ if startsWith(vpair.key, 'target_') }}:
          ${{ vpair.key }}:
            target_id: ${{ vpair.key }}
            target_kabob: ${{ vpair.value }}

  steps:
  - template: set-deployment-variables-steps.yml
  - template: cross-build-steps.yml
    parameters:
      platform: $(target_kabob)
  - script: |
      set -xeuo pipefail
      cd target/$(target_kabob)/release
      curl --proto '=https' --tlsv1.2 -sSfL "$TOOL_URL" |tar xz
      artifact="tectonic-$(version_text)-$(target_kabob).tar.gz"
      tar czf $artifact tectonic
      ./ttcitool upload-gh-artifact $artifact
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      TOOL_URL: https://github.com/tectonic-typesetting/tectonic-ci-support/releases/download/production/ttcitool-latest-x86_64-unknown-linux-gnu.tar.gz

- job: build_and_deploy_semistatic_macos
  pool:
    vmImage: macOS-10.13  # vcpkg has a finicky build that currently requires this
  steps:
  - template: set-deployment-variables-steps.yml
  - template: semistatic-macos-build-steps.yml
  - script: |
      set -xeuo pipefail
      cd target/release
      curl --proto '=https' --tlsv1.2 -sSfL "$TOOL_URL" |tar xz
      artifact="tectonic-$(version_text)-x86_64-apple-darwin.tar.gz"
      tar czf $artifact tectonic
      ./ttcitool upload-gh-artifact $artifact
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      TOOL_URL: https://github.com/tectonic-typesetting/tectonic-ci-support/releases/download/production/ttcitool-latest-x86_64-apple-darwin.tar.gz
