# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# Steps to set common variables used during deploymen: `tag_name`, `version_text`.

steps:
  - bash: |
      echo "##vso[task.setvariable variable=tag_name]${BUILD_SOURCEBRANCH#refs/tags/}"
      case $BUILD_SOURCEBRANCH in
      refs/tags/continuous) echo "##vso[task.setvariable variable=version_text]latest" ;;
      refs/tags/v*) echo "##vso[task.setvariable variable=version_text]${BUILD_SOURCEBRANCH#refs/tags/v}" ;;
      *) exit 1 ;;
      esac
    displayName: Set deployment variables
